name: Karate Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  karate-tests:
    name: Run Karate Tests
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      # Step 3: Set up Maven
      - name: Set up Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      # Step 4: Build and run tests
      - name: Run Karate Tests
        env:
          EMAIL: ${{ vars.EMAIL }}  # Secrets'den EMAIL al覺n覺yor
          PASSWORD: ${{ vars.PASSWORD }}  # Secrets'den PASSWORD al覺n覺yor
        run: |
          mvn clean test

      # Step 5: Upload Karate Reports (Optional)
      - name: Upload Karate Reports
        uses: actions/upload-artifact@v4
        with:
          name: karate-reports
          path: target/karate-reports/
